CREATE TABLE movie (
	id BIGINT generated by default as identity,
	movie_year INT,
	title VARCHAR(4000),
	winner BOOLEAN,
	primary key (id)
);

create table movie_producer (
	id bigint generated by default as identity,
	movie_id bigint,
	producer_id bigint,
	primary key (id)
);

create table movie_studio (
	id bigint generated by default as identity,
	movie_id bigint,
	studio_id bigint,
	primary key (id)
);

create table producer (
	id bigint generated by default as identity,
	name varchar(255),
	primary key (id)
);

create table studio (
	id bigint generated by default as identity,
	name varchar(255),
	primary key (id)
);

alter table movie_producer add constraint movie_producer_movie_id foreign key (movie_id) references movie;
alter table movie_producer add constraint movie_producer_producer_id foreign key (producer_id) references producer;
alter table movie_studio add constraint movie_studio_movie_id foreign key (movie_id) references movie;
alter table movie_studio add constraint movie_studio_producer_id foreign key (studio_id) references studio;
